### ISSUE TITLE
[Improvement][api] Introduce interface about api module service

### ISSUE THREAD

**Issue by yangyichao-mango** [apache/incubator-dolphinscheduler#3369]
**Describe the question**
Introduce interface about api module service for clearly service module.

**What are the current deficiencies and the benefits of improvement**
- A clear and concise service will help contributor or user to ready the code and locate the function.

**Which version of DolphinScheduler:**
 -[dev]

**Describe alternatives you've considered**
Introduce service interface

**Comment by yangyichao-mango** [comment]
- [ ] AccessTokenService
- [ ] AlertGroupService
- [ ] BaseService
- [ ] DataAnalysisService
- [ ] DataSourceService
- [ ] ExecutorService
- [ ] LoggerService
- [ ] MonitorService
- [ ] ProcessDefinitionService
- [ ] ProcessInstanceService
- [ ] ProjectService
- [ ] QueueService
- [ ] ResourcesService
- [ ] SchedulerService
- [ ] SessionService
- [ ] TaskInstanceService
- [ ] TaskRecordService
- [ ] TenantService
- [ ] UdfFuncService
- [ ] UserAlertGroupService
- [ ] UsersService
- [ ] WorkerGroupService
- [ ] WorkFlowLineageService

**Comment by yangyichao-mango** [comment]
Tag: easy to implement, welcome to contribute~

**Comment by CalvinKirs** [comment]
Hi, I noticed that there is a lot of code smell in your pr about this problem, can you solve it?and there are many conflicting files in the related PR that need to be resolved, please solve it first.

**Comment by chengshiwen** [comment]
@CalvinKirs Assign to me. I will resolve all the related PRs by yangyichao-mango
- [x] #4758: AlertGroupService, UsersService (Resolve #3417)
- [x] #4759: DataSourceService, ExecutorService (Resolve #3440)
- [x] #4765: MonitorService, ProcessInstanceService, QueueService (Resolve #3443)
- [x] #4766: ResourcesService, SchedulerService, TaskInstanceService (Resolve #3444)
- [x] #4768: TaskRecordService , UdfFuncService, WorkFlowLineageService, WorkerGroupService (Resolve #3445)

**Comment by chengshiwen** [comment]
@CalvinKirs I have resolved all the related PRs by yangyichao-mango.

**Comment by CalvinKirs** [comment]
> @CalvinKirs I have resolved all the related PRs by yangyichao-mango.

I noticed that there are some code smells in the pr you submitted, it is best to solve them. (Some may not be a real bad code smell)

**Comment by chengshiwen** [comment]
> > @CalvinKirs I have resolved all the related PRs by yangyichao-mango.
> 
> I noticed that there are some code smells in the pr you submitted, it is best to solve them. (Some may not be a real bad code smell)

@CalvinKirs Those code smells already exist in the previous code, and are not introduced by me. I have tried to fix some bugs, vulnerabilities, security hotspots and code smells.

Such as the previous pr #3440, you can see **2 vulnerabilities, 1 security hotspot and 34 code smells**, while in the new pr #4759, there are only **27 code smells**.

**Comment by chengshiwen** [comment]
Compared to pr #3417 with **20 code smells** half year ago, there are **22 code smells** in the new pr #4758.

Compared to pr #3440 with **2 vulnerabilities, 1 security hotspot and 34 code smells** half year ago, there are only **27 code smells** in new pr #4759.

Compared to pr #3443 with **2 vulnerabilities, 15 code smells and 1.4% duplication** half year ago, there are only **17 code smells** in the new pr #4765.

Compared to pr #3444 with **9 vulnerabilities, 74 code smells and 5.5% duplication** half year ago, there are only **97 code smells and 2.4% duplication** in the new pr #4766.

Compared to pr #3445 with **2 vulnerabilities and 18 code smells** half year ago, there are only **26 code smells** in the new pr #4768.
